[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
